package com.backend.ord.features.gpt_tokens_usage_log.variants.word_tokens_usage.repository

import com.backend.ord.enums.persistence.tokens_usage.WordsGPTTokensConsumptionType
import com.backend.ord.features.gpt_tokens_usage_log.variants.shared.repository.TokensUsageRepository
import com.backend.ord.features.gpt_tokens_usage_log.variants.word_tokens_usage.model.WordTokensUsage
import org.springframework.stereotype.Repository

@Repository
interface WordTokensUsageRepository : TokensUsageRepository<WordTokensUsage, WordsGPTTokensConsumptionType>