package com.backend.ord.domain.application.games.crossword

import com.backend.ord.domain.application.games.crossword.board.Coordinates
import com.backend.ord.domain.application.games.crossword.board.CrosswordWordDirection
import java.util.*

/**
 * Represents an individual question used in an AI-generated crossword puzzle.
 *
 * @property id Unique identifier for the question, automatically generated by default.
 * @property word The word randomly taken from the user's saved words in DB. Example: "unbelievable".
 * @property clue The AI generated clue for the question. Example: For word "unbelievable", the clue could be "Astounding and difficult to surprising".
 * @property lettersInAnswer List of all letters from the word, which contribute to the main answer of the crossword.
 * @property position The position of the question on the board, initially null since it's not placed on the board yet by the AI.
 */
data class CrosswordQuestion(
    val id: UUID = UUID.randomUUID(),

    var word: String,
    val clue: String,

    var lettersInAnswer: MutableList<LetterInCrosswordAnswer>? = null,

    var position: QuestionBoardPosition? = null
)

/**
 * Adds a new answer component to the list of answer components.
 */
fun CrosswordQuestion.addAnswerComponent(
    indexInWord: Int,
    indexInPassword: Int
) {
    if (lettersInAnswer == null) lettersInAnswer = mutableListOf<LetterInCrosswordAnswer>()

    lettersInAnswer?.add(
        LetterInCrosswordAnswer(
            indexInWord = indexInWord,
            indexInPassword = indexInPassword
        )
    )
}

fun CrosswordQuestion.removeAnswerComponents(passwordIndexes: Set<Int>) {
    lettersInAnswer = lettersInAnswer?.filter { it.indexInPassword !in passwordIndexes }?.toMutableList()
}

/**
 * Returns the coordinates of the letter at the given index in the word.
 */
fun CrosswordQuestion.getCoordinatesOfLetterAtIndex(index: Int): Coordinates {
    val position = position ?: throw IllegalStateException("The question is not placed on the board yet.")

    val (x, y) = position.coordinates.start

    return when (position.direction) {
        CrosswordWordDirection.HORIZONTAL -> Coordinates(x + index, y)
        CrosswordWordDirection.VERTICAL -> Coordinates(x, y + index)
    }
}
