package com.ord.core.gpt_tokens_usage_analytics.responses.dto

import io.swagger.v3.oas.annotations.media.Schema

@Schema(description = "Aggregated tokens usage for a specific operation type")
data class TokensUsageByOperationTypeDTO(
    @Schema(description = "Type of operation", example = "CONVERSATION_AI_RESPONSE")
    val operationType: String,

    @Schema(description = "Total input tokens consumed by this operation type", example = "5000")
    val inputTokens: Long,

    @Schema(description = "Total output tokens generated by this operation type", example = "3000")
    val outputTokens: Long,

    @Schema(description = "Number of times this operation was performed", example = "42")
    val count: Long
)
