### General ###
server.port=${APP_PORT}
spring.profiles.active=${SPRING_PROFILE}
spring.application.name=ord-backend
spring.jpa.properties.hibernate.jdbc.time_zone=UTC+1
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false
### JWT
jwt.auth_cookie_name=AUTH-TOKEN
jwt.user_id_claim_name=user_id
jwt.secret_key=${JWT_SECRET_KEY}
jwt.expiration_time=${JWT_EXPIRATION_TIME}
### Open AI
openai.temperature=1
openai.max_tokens=4096
openai.api_key=${OPEN_AI_KEY}
openai.gpt_model=gpt-4.1-mini
openai.api_url=https://api.openai.com/v1/responses
openai.price_per_mln_input_tokens=0.150
openai.price_per_mln_output_tokens=0.600
openai.maximum_number_of_open_ai_api_request_attempts=5
### Dev logging ###
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.com.ord=DEBUG
# Show SQL statements in the console
#spring.jpa.show-sql=true
#
## Format SQL queries for better readability
#spring.jpa.properties.hibernate.format_sql=true
#
## Log the parameter values in SQL queries (useful for debugging)
#spring.jpa.properties.hibernate.highlight_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.generate_statistics=true
#
## Set the log level to DEBUG to see detailed Hibernate logs
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

