### General ###
spring.profiles.active=${SPRING_PROFILE}
spring.application.name=ord-backend
spring.jpa.properties.hibernate.jdbc.time_zone=UTC+1

### JWT
jwt.auth_cookie_name=AUTH-TOKEN
jwt.secret_key=${JWT_SECRET_KEY}
jwt.expiration_time=${JWT_EXPIRATION_TIME}