package com.backend.ord.services.ai.dto

import com.backend.ord.domain.application.games.Coordinates
import com.backend.ord.domain.persistence.embedded.game_instructions.AnswerComponent
import com.backend.ord.domain.persistence.embedded.game_instructions.CrosswordWordDirection
import java.util.*


/**
 * Represents the position of a question on the crossword board.
 *
 * @property coordinates The (X,Y) position of the question on the board.
 * @property direction The direction of the question on the board, either horizontal or vertical.
 */
data class QuestionBoardPosition(
    val coordinates: Coordinates,
    val direction: CrosswordWordDirection
)

/**
 * Represents an individual question used in an AI-generated crossword puzzle.
 *
 * @property id Unique identifier for the question, automatically generated by default.
 * @property word The word randomly taken from the user's saved words in DB. Example: "unbelievable".
 * @property clue The AI generated clue for the question. Example: For word "unbelievable", the clue could be "Astounding and difficult to surprising".
 * @property answerComponents List of all letters from the word, which contribute to the main answer of the crossword.
 * @property position The position of the question on the board, initially null since it's not placed on the board yet by the AI.
 */
data class AIGeneratedCrosswordQuestion(
    val id: UUID = UUID.randomUUID(),

    var word: String,
    val clue: String,

    var answerComponents: MutableList<AnswerComponent>? = null,

    var position: QuestionBoardPosition? = null
)

/**
 * Represents a crossword generated by the AI (returned from the GenAI API response).
 *
 * @property answer
 *   The main answer of the crossword—constructed from letters of the answers to the
 *   questions on the board.
 *   **Example**: For a crossword consisting of 12 questions, it could be `"audacity"`.
 * @property answerExplanation
 *   The explanation of the answer.
 *   Example: For the answer `"audacity"`, it could be
 *   `"boldness or daring, especially with confident or arrogant disregard for personal safety,
 *   conventional thought, or other restrictions."`
 * @property questions
 *   The list of questions that make up the crossword board.
 */
data class AIGeneratedCrossword(
    var answer: String,
    val answerExplanation: String,

    val questions: List<AIGeneratedCrosswordQuestion>
)