package com.ord.features.game.variants.crossword.ai.dto.openai

import com.ord.features.game.variants.crossword.ai.dto.AIGeneratedCrossword
import com.ord.features.game.variants.crossword.dto.helpers.question.CrosswordQuestion

/**
 * Intermediate DTO for OpenAI structured outputs response for crossword generation.
 *
 * This DTO matches OpenAI's structured output schema where all fields are required.
 * The CrosswordQuestion fields that are nullable in the domain model are handled
 * at the domain level (lettersInAnswer and position are set later during board construction).
 *
 * Use `toDomain()` to convert this to `AIGeneratedCrossword` for application use.
 */
data class OpenAICrossword(
    val answer: String,
    val answerExplanation: String,
    val questions: List<OpenAICrosswordQuestion>
)

/**
 * Intermediate version of CrosswordQuestion for OpenAI structured outputs.
 * Only includes the fields that are generated by AI (word and clue).
 * The lettersInAnswer and position fields are set later during board construction.
 */
data class OpenAICrosswordQuestion(
    val word: String,
    val clue: String
) {
    fun toDomain(): CrosswordQuestion {
        return CrosswordQuestion(
            word = word,
            clue = clue,
            lettersInAnswer = null,  // Set later during board construction
            position = null           // Set later during board construction
        )
    }
}

/**
 * Extension function to convert the entire OpenAI response to domain model.
 */
fun OpenAICrossword.toDomain(): AIGeneratedCrossword {
    return AIGeneratedCrossword(
        answer = answer,
        answerExplanation = answerExplanation,
        questions = questions.map { it.toDomain() }
    )
}
