package com.ord.features.game.variants.crossword.ai.dto

import com.ord.features.game.variants.crossword.dto.helpers.question.CrosswordQuestion

/**
 * Represents a crossword generated by the AI (returned from the GenAI API response).
 *
 * @property answer
 *   The main answer of the crossword—constructed from letters of the answers to the
 *   questions on the board.
 *   **Example**: For a crossword consisting of 12 questions, it could be `"audacity"`.
 * @property answerExplanation
 *   The explanation of the answer.
 *   Example: For the answer `"audacity"`, it could be
 *   `"boldness or daring, especially with confident or arrogant disregard for personal safety,
 *   conventional thought, or other restrictions."`
 * @property questions
 *   The list of questions that make up the crossword board.
 */
data class AIGeneratedCrossword(
    var answer: String,
    val answerExplanation: String,

    val questions: List<CrosswordQuestion>
)