name: 🚀 Build, Test & Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: ⚙️ Set up Maven 3.9
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: 🧪 Run tests with Maven
        run: |
          mvn -Dtest=com.ord.AllTestsSuite test
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
          SPRING_PROFILE: 'test'
          ENV_TEST_PROPERTY: '1test1'


      - name: 🔨 Package app
        run: mvn clean package -DskipTests

      - name: 🐳 Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: 🔐 Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: 🚀 Push Docker image to Heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: 🔄 Release to Heroku
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/formation \
          -d '{"updates":[{"type":"web","docker_image":"'"$(docker inspect registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web --format={{.Id}})"'"}]}' \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}"

